#############################################################################
# Makefile for building: TRPO.app/Contents/MacOS/TRPO
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ????. 27 21:35:19 2011
# Project:  TRPO.pro
# Template: app
# Command: /Developer/Qt/Desktop/Qt/474/gcc/bin/qmake -spec /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/macx-g++ CONFIG+=release -o Makefile TRPO.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/macx-g++ -I. -I/Developer/Qt/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I/Developer/Qt/Desktop/Qt/474/gcc/include/QtCore -I/Developer/Qt/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I/Developer/Qt/Desktop/Qt/474/gcc/include/QtGui -I/Developer/Qt/Desktop/Qt/474/gcc/include -I/users/poed/Desktop/development/vstu_dev/460e/Jukova\ TRPO/TRPO -I/users/poed/Desktop/development/vstu_dev/460e/Jukova\ TRPO/TRPO -F/Developer/Qt/Desktop/Qt/474/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Developer/Qt/Desktop/Qt/474/gcc/lib -L/Developer/Qt/Desktop/Qt/474/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Developer/Qt/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		utoolbarview.cpp \
		uarrow.cpp \
		uarrowsegment.cpp \
		ubox.cpp moc_mainwindow.cpp \
		moc_utoolbarview.cpp \
		moc_uarrow.cpp \
		moc_uarrowsegment.cpp \
		moc_ubox.cpp
OBJECTS       = main.o \
		mainwindow.o \
		utoolbarview.o \
		uarrow.o \
		uarrowsegment.o \
		ubox.o \
		moc_mainwindow.o \
		moc_utoolbarview.o \
		moc_uarrow.o \
		moc_uarrowsegment.o \
		moc_ubox.o
DIST          = /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		TRPO.pro
QMAKE_TARGET  = TRPO
DESTDIR       = 
TARGET        = TRPO.app/Contents/MacOS/TRPO

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile TRPO.app/Contents/PkgInfo TRPO.app/Contents/Resources/empty.lproj TRPO.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) TRPO.app/Contents/MacOS/ || $(MKDIR) TRPO.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TRPO.pro  /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/macx-g++/qmake.conf /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/macx-g++ CONFIG+=release -o Makefile TRPO.pro
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/release.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
/Developer/Qt/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/macx-g++ CONFIG+=release -o Makefile TRPO.pro

TRPO.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) TRPO.app/Contents || $(MKDIR) TRPO.app/Contents 
	@$(DEL_FILE) TRPO.app/Contents/PkgInfo
	@echo "APPL????" >TRPO.app/Contents/PkgInfo
TRPO.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) TRPO.app/Contents/Resources || $(MKDIR) TRPO.app/Contents/Resources 
	@touch TRPO.app/Contents/Resources/empty.lproj
	
TRPO.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) TRPO.app/Contents || $(MKDIR) TRPO.app/Contents 
	@$(DEL_FILE) TRPO.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,TRPO,g" -e "s,@TYPEINFO@,????,g" /Developer/Qt/Desktop/Qt/474/gcc/mkspecs/macx-g++/Info.plist.app >TRPO.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/TRPO1.0.0 || $(MKDIR) .tmp/TRPO1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TRPO1.0.0/ && $(COPY_FILE) --parents mainwindow.h utoolbarview.h uarrow.h uarrowsegment.h ubox.h .tmp/TRPO1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp utoolbarview.cpp uarrow.cpp uarrowsegment.cpp ubox.cpp .tmp/TRPO1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/TRPO1.0.0/ && (cd `dirname .tmp/TRPO1.0.0` && $(TAR) TRPO1.0.0.tar TRPO1.0.0 && $(COMPRESS) TRPO1.0.0.tar) && $(MOVE) `dirname .tmp/TRPO1.0.0`/TRPO1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TRPO1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r TRPO.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_utoolbarview.cpp moc_uarrow.cpp moc_uarrowsegment.cpp moc_ubox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_utoolbarview.cpp moc_uarrow.cpp moc_uarrowsegment.cpp moc_ubox.cpp
moc_mainwindow.cpp: utoolbarview.h \
		mainwindow.h
	/Developer/Qt/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

moc_utoolbarview.cpp: utoolbarview.h
	/Developer/Qt/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ utoolbarview.h -o moc_utoolbarview.cpp

moc_uarrow.cpp: uarrow.h
	/Developer/Qt/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ uarrow.h -o moc_uarrow.cpp

moc_uarrowsegment.cpp: uarrowsegment.h
	/Developer/Qt/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ uarrowsegment.h -o moc_uarrowsegment.cpp

moc_ubox.cpp: ubox.h
	/Developer/Qt/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ubox.h -o moc_ubox.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/Developer/Qt/Desktop/Qt/474/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		utoolbarview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		utoolbarview.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

utoolbarview.o: utoolbarview.cpp utoolbarview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utoolbarview.o utoolbarview.cpp

uarrow.o: uarrow.cpp uarrow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uarrow.o uarrow.cpp

uarrowsegment.o: uarrowsegment.cpp uarrowsegment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uarrowsegment.o uarrowsegment.cpp

ubox.o: ubox.cpp ubox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ubox.o ubox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_utoolbarview.o: moc_utoolbarview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_utoolbarview.o moc_utoolbarview.cpp

moc_uarrow.o: moc_uarrow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uarrow.o moc_uarrow.cpp

moc_uarrowsegment.o: moc_uarrowsegment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uarrowsegment.o moc_uarrowsegment.cpp

moc_ubox.o: moc_ubox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ubox.o moc_ubox.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

